name: SDKs Instrumented Tests
description: 'Runs various Kotlin SDK instrumented tests'

inputs:
  name:
    description: 'Name of test and emulator'
    required: true
  command:
    description: 'Gradle task being run'
    required: true
  projectId:
    description: 'WalletConnect projectId'
    required: true
  notifyProjectId:
    description: 'GM Dapp projectId'
    required: false
  notifySecret:
    description: 'GM Dapp secret'
    required: false
  testTimeoutSeconds:
    description: 'Seconds for test timeout'
    default: '120'
  walletPrivateKey:
    description: 'Test wallet private key for Pay SDK tests'
    required: false
  merchantApiKey:
    description: 'Merchant API key for Pay SDK tests'
    required: false

runs:
  using: "composite"
  steps:
    - name: Create log file
      shell: bash
      run: |
        touch emulator.log
        chmod 777 emulator.log
        adb logcat -s "WalletConnectV2" >> emulator.log &

    - name: Accept Android Licenses
      uses: SimonMarquis/android-accept-licenses@v1

    - name: Run instrumented tests
      shell: bash
      env:
        WC_CLOUD_PROJECT_ID: ${{ inputs.projectId}}
        TEST_TIMEOUT_SECONDS: ${{ inputs.testTimeoutSeconds }}
        NOTIFY_INTEGRATION_TESTS_PROJECT_ID: ${{ inputs.notifyProjectId }}
        NOTIFY_INTEGRATION_TESTS_SECRET: ${{ inputs.notifySecret }}
        TEST_WALLET_PRIVATE_KEY: ${{ inputs.walletPrivateKey }}
        MERCHANT_API_KEY: ${{ inputs.merchantApiKey }}
      run: ./gradlew ${{ inputs.command }} -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect

    - uses: actions/upload-artifact@v5
      if: always()
      with:
        name: ${{ inputs.name }}
        path: |
          **/reports/**
          emulator.log