name: E2E Tests with Maestro

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
  workflow_dispatch:

jobs:
  build_internal_samples:
    strategy:
      matrix:
        conf: [
          { name: wallet, command: ":sample:wallet:assembleInternal" },
          { name: dapp, command: ":sample:dapp:assembleInternal" },
        ]
    name: Build Internal ${{ matrix.conf.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x86_64
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Required files to build samples
        with:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          FIREBASE_SERVICE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
          SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
          ENCODED_STRING_DEBUG: ${{ secrets.WC_KOTLIN_DEBUG_KEYSTORE }}
          SIGNING_KEY_STORE_PATH_DEBUG: ${{ secrets.WC_KOTLIN_DEBUG_KEYSTORE_PATH }}
          ENCODED_STRING_INTERNAL: ${{ secrets.WC_KOTLIN_INTERNAL_KEYSTORE }}
          SIGNING_KEY_STORE_PATH_INTERNAL: ${{ secrets.WC_KOTLIN_INTERNAL_KEYSTORE_PATH }}
          ENCODED_STRING_UPLOAD: ${{ secrets.WC_KOTLIN_UPLOAD_KEYSTORE }}
          SIGNING_KEY_STORE_PATH_UPLOAD: ${{ secrets.WC_KOTLIN_UPLOAD_KEYSTORE_PATH }}
        uses: ./.github/actions/ci_setup

      - name: Build sample - Internal
        env:
          WC_CLOUD_PROJECT_ID: ${{ secrets.WC_CLOUD_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          NOTIFY_INTEGRATION_TESTS_PROJECT_ID: ${{ secrets.NOTIFY_INTEGRATION_TESTS_PROJECT_ID }}
          NOTIFY_INTEGRATION_TESTS_SECRET: ${{ secrets.NOTIFY_INTEGRATION_TESTS_SECRET }}
          MIX_PANEL: ${{ secrets.MIX_PANEL }}
        run: |
          ./gradlew ${{ matrix.conf.command }}

      - name: List built APKs for debugging
        run: |
          echo "=== Built APKs ==="
          find sample/${{ matrix.conf.name }}/build/outputs/apk -name "*.apk" -exec ls -la {} \;
          echo "=== APK Info ==="
          find sample/${{ matrix.conf.name }}/build/outputs/apk -name "*.apk" -exec aapt dump badging {} \; || true

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.conf.name }}-apk
          path: sample/${{ matrix.conf.name }}/build/outputs/apk/internal/*.apk
          retention-days: 7  # Increased retention for debugging

  run_e2e_tests:
    name: Run E2E Tests
    timeout-minutes: 30
    runs-on: ubuntu-16core
    needs: build_internal_samples
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download all APKs
        uses: actions/download-artifact@v4
        with:
          pattern: "*-apk"
          path: apks
          merge-multiple: true

      - name: List APKs
        run: |
          echo "Available APKs:"
          find apks -name "*.apk" | xargs ls -la

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          export PATH="$PATH":"$HOME/.maestro/bin"
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
          maestro --version

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Start Android Emulator and Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          ram-size: 4096M
          heap-size: 576M
          emulator-boot-timeout: 900
          profile: pixel_6
          avd-name: test_device
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save -no-snapshot-load
          disable-animations: true
          pre-emulator-launch-script: |
            echo "Running pre emulator launch script"
            pwd
          script: |
            # Setup debug directory
            mkdir -p debug-artifacts
            
            # Wait for emulator to be fully ready
            echo "Waiting for emulator to be ready..."
            adb wait-for-device
            
            # Wait for boot completion
            echo "Waiting for boot completion..."
            adb shell 'while [ "$(getprop sys.boot_completed)" != "1" ]; do sleep 2; done'
            echo "Boot completed!"
            
            echo "Emulator booted successfully"
            adb devices
            
            # Clear logcat before we start
            adb logcat -c
            
            # Start logcat capture in background
            adb logcat > debug-artifacts/full-logcat.txt &
            LOGCAT_PID=$!
            
            # Install APKs - simplified approach
            echo "Installing APKs:"
            ls -la apks/
            
            # Install each APK individually with explicit checks
            if [ -f "apks/wallet-internal-release.apk" ]; then
              echo "Installing wallet APK..."
              adb install -r "apks/wallet-internal-release.apk"
            fi
            
            if [ -f "apks/dapp-internal-release.apk" ]; then
              echo "Installing dapp APK..."
              adb install -r "apks/dapp-internal-release.apk"
            fi
            
            # Install any other APKs found - using safer approach
            echo "Looking for additional APKs to install..."
            for apk_file in apks/*.apk; do
              if [ -f "$apk_file" ]; then
                echo "Installing: $apk_file"
                adb install -r "$apk_file" || echo "Failed to install $apk_file"
              fi
            done
            
            # Verify installations
            echo "=== Verifying installed apps ==="
            adb shell pm list packages | grep -E "com.reown.sample" || echo "No reown sample apps found"
            
            # Simple package check
            echo "=== Package details ==="
            if adb shell pm list packages | grep -q "com.reown.sample.wallet"; then
              echo "Wallet app found"
            else
              echo "Wallet app not found"
            fi
            
            if adb shell pm list packages | grep -q "com.reown.sample.dapp"; then
              echo "DApp found"
            else
              echo "DApp not found"
            fi
            
            # Check APK info
            echo "Checking APK details:"
            adb shell dumpsys package com.reown.sample.wallet.internal | grep -A 5 "versionName"
            
            # Clear app data
            echo "Clearing app data..."
            adb shell pm clear com.reown.sample.wallet.internal || true
            adb shell pm clear com.reown.sample.dapp.internal || true
            
            # Grant runtime permissions that might be needed
            echo "Granting permissions..."
            adb shell pm grant com.reown.sample.wallet.internal android.permission.INTERNET || true
            adb shell pm grant com.reown.sample.wallet.internal android.permission.ACCESS_NETWORK_STATE || true
            adb shell pm grant com.reown.sample.wallet.internal android.permission.ACCESS_WIFI_STATE || true
            adb shell pm grant com.reown.sample.wallet.internal android.permission.CAMERA || true
            
            # Check if the app needs to be enabled
            echo "Checking app state..."
            if adb shell pm list packages -d | grep -q "com.reown.sample.wallet.internal"; then
              echo "App is disabled, enabling it..."
              adb shell pm enable com.reown.sample.wallet.internal
            else
              echo "App is not disabled"
            fi
            
            # Wait for system to settle
            sleep 10
            
            # Check available activities
            echo "Checking available activities for wallet app:"
            adb shell dumpsys package com.reown.sample.wallet.internal | grep -A 10 "Activity" || true
            
            # Wait and capture state
            sleep 10
            
            # Capture comprehensive debug info
            echo "=== CAPTURING DEBUG INFO ==="
            
            # Window state
            echo "Window state:" > debug-artifacts/window_state.txt
            adb shell dumpsys window windows >> debug-artifacts/window_state.txt
            
            # Current activity
            echo "Current activity:" > debug-artifacts/current_activity.txt
            adb shell dumpsys activity activities | grep -E "mResumedActivity|mFocusedActivity" >> debug-artifacts/current_activity.txt
            
            # Check for crashes
            echo "Checking for crashes..."
            adb logcat -d | grep -E "FATAL EXCEPTION|AndroidRuntime|Process.*com.reown" > debug-artifacts/crashes.txt || echo "No crashes found" > debug-artifacts/crashes.txt
            
            # ANR traces
            adb shell ls /data/anr/ > debug-artifacts/anr_list.txt 2>&1 || true
            
            # Memory info
            adb shell dumpsys meminfo com.reown.sample.wallet.internal > debug-artifacts/meminfo.txt || true
            
            # App process info
            adb shell ps | grep reown > debug-artifacts/processes.txt || true
            
            # Network state (important for WalletConnect)
            echo "Network state:" > debug-artifacts/network_state.txt
            adb shell dumpsys connectivity >> debug-artifacts/network_state.txt
            adb shell settings get global airplane_mode_on >> debug-artifacts/network_state.txt
            
            # Force stop before Maestro tests
            adb shell am force-stop com.reown.sample.wallet.internal
            adb shell am force-stop com.reown.sample.dapp.internal
            sleep 5
            
            # === WHITE SCREEN DEBUGGING ===
            echo "=== DEBUGGING WHITE SCREEN ISSUE ==="
            
            # Try to launch the app manually before Maestro
            echo "Attempting manual app launch..."
            
            # Launch the app using simple approach
            echo "Launching wallet app..."
            adb shell am start -n com.reown.sample.wallet.internal/.ui.WalletKitActivity || true
            
            # Fallback launch method
            echo "Checking if app is running after initial launch..."
            app_running=$(adb shell ps | grep -c "com.reown.sample.wallet.internal" || echo "0")
            if [ "$app_running" -eq 0 ]; then
              echo "Fallback: using monkey to launch"
              adb shell monkey -p com.reown.sample.wallet.internal -c android.intent.category.LAUNCHER 1 || true
            fi
            
            sleep 15
            
            # Check if app is running
            echo "Final check if app is running..."
            app_running=$(adb shell ps | grep -c "com.reown.sample.wallet.internal" || echo "0")
            if [ "$app_running" -gt 0 ]; then
              echo "✅ Wallet app is running"
            else
              echo "❌ Wallet app is NOT running"
              adb shell am start -n com.reown.sample.wallet.internal/com.reown.sample.wallet.ui.WalletKitActivity || true
              sleep 10
            fi
            
            # Take screenshots at different stages
            echo "Taking screenshots for white screen analysis..."
            adb shell screencap /sdcard/screenshot_after_launch.png
            adb pull /sdcard/screenshot_after_launch.png debug-artifacts/ || true
            
            # Check for any startup errors
            echo "Checking for startup errors..."
            adb logcat -d > debug-artifacts/temp_logcat.txt || true
            if [ -f debug-artifacts/temp_logcat.txt ]; then
              grep -E "com.reown.sample.wallet.internal.*E/|FATAL.*com.reown" debug-artifacts/temp_logcat.txt > debug-artifacts/wallet_errors.txt || echo "No errors found" > debug-artifacts/wallet_errors.txt
              rm -f debug-artifacts/temp_logcat.txt
            fi
            
            # Check current activity and window focus - simplified
            echo "Current activity and window state:"
            adb shell dumpsys activity activities > debug-artifacts/activity_state.txt || true
            adb shell dumpsys window windows > debug-artifacts/window_focus.txt || true
            
            # Check app state - simplified
            echo "=== App State Check ==="
            adb shell pm dump com.reown.sample.wallet.internal > debug-artifacts/app_permissions.txt || true
            
            # Force a fresh launch after clearing state
            adb shell am force-stop com.reown.sample.wallet.internal
            sleep 5
            echo "Fresh launch attempt..."
            adb shell am start -W -n com.reown.sample.wallet.internal/.ui.WalletKitActivity 2>&1 | tee debug-artifacts/fresh_launch.txt || true
            sleep 15
            
            # Final screenshot
            adb shell screencap /sdcard/screenshot_fresh_launch.png
            adb pull /sdcard/screenshot_fresh_launch.png debug-artifacts/ || true
            
            # Check current activity
            echo "Current activity before Maestro:"
            adb shell dumpsys activity activities > debug-artifacts/current_activity_maestro.txt || true
            if [ -f debug-artifacts/current_activity_maestro.txt ]; then
              grep -E "mResumedActivity|mFocusedActivity" debug-artifacts/current_activity_maestro.txt || echo "No resumed/focused activity found"
            fi
            
            # DO NOT kill the app here - let's see if it's actually running properly
            echo "App state check complete, proceeding with Maestro tests..."
            
            echo "Running Maestro native to native tests:"
            maestro test .maestro/flows/native/connect_reject.yaml
            # maestro test .maestro/flows/native/connect_confirm.yaml
            # maestro test .maestro/flows/native/personal_sign_reject.yaml
            # maestro test .maestro/flows/native/personal_sign_confirm.yaml
            
            # Stop logcat capture
            kill $LOGCAT_PID || true
            
            # Filter logcat for relevant info
            if [ -f debug-artifacts/full-logcat.txt ]; then
              grep -E "reown|WalletConnect|AndroidRuntime|System.err|ActivityManager" debug-artifacts/full-logcat.txt > debug-artifacts/filtered-logcat.txt || echo "No relevant log entries found" > debug-artifacts/filtered-logcat.txt
            fi

      - name: Analyze crash logs
        if: always()
        run: |
          if [ -f debug-artifacts/crashes.txt ] && [ -s debug-artifacts/crashes.txt ]; then
            echo "::error::App crashes detected:"
            cat debug-artifacts/crashes.txt
          fi
          
          if [ -f debug-artifacts/filtered-logcat.txt ]; then
            echo "Relevant log entries:"
            tail -n 100 debug-artifacts/filtered-logcat.txt
          fi

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: debug-artifacts/
          if-no-files-found: warn

      - name: Upload Maestro artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-artifacts
          path: |
            .maestro/
            videos/
            *.mp4
            *.mov
          if-no-files-found: warn